### ISSUE TITLE
Plugin breaks Android resources

### ISSUE THREAD

**Issue by drewhamilton** [JakeWharton/OverloadReturn#2]
When I apply this plugin to an Android library module, some instrumented tests that use test resources start breaking at test-runtime. This is before I have actually used the compiler or added the annotation dependency.

I'm not sure if the problem is due to the test resources, no support for Android/dex in general, or just something that went stale in the last 2 years.

Here's the stacktrace:
```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/appcompat/resources/R$drawable;
	at androidx.appcompat.widget.ResourceManagerInternal.checkVectorDrawableSetup(ResourceManagerInternal.java:489)
	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:137)
	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:132)
	at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:104)
	at com.backbase.deferredresources.DeferredDrawable$Resource.resolve(DeferredDrawable.kt:59)
	at com.backbase.deferredresources.DeferredDrawableJavaTest.resourceConstructor_withTransformationFunction_syntaxWorks(DeferredDrawableJavaTest.java:23)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2205)
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.appcompat.resources.R$drawable" on path: DexPathList[[zip file "/data/app/~~IyjOZnnoi66gAaq1NQUSYg==/com.backbase.deferredresources.test-4BRR0oYZwbvkAImbUhX9yw==/base.apk"],nativeLibraryDirectories=[/data/app/~~IyjOZnnoi66gAaq1NQUSYg==/com.backbase.deferredresources.test-4BRR0oYZwbvkAImbUhX9yw==/lib/x86, /system/lib, /system_ext/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 37 more
```

It seems notable that the missing class is also not available at compile time of my library, at least according to the IDE's syntax highlighting on the line (ResourceManagerInternal.java:489).

The issue is reproducible by running `./gradlew :deferred-resources:connectedCheck` on [this branch](https://github.com/Backbase/DeferredResources/tree/overload-return) of my library.

**Comment by drewhamilton** [comment]
I ended up using `@JvmSynthetic` to do this manually and I'm deleting my old branch so closing this.
